<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ITUs-MacBook-Pro-5.local" name="edu.itu.bridge.tests.ui.staff.UI_StaffViewPage_OLD" tests="3" failures="0" timestamp="26 Jan 2015 22:40:38 GMT" time="10.258" errors="2">
  <testcase name="ui_StaffViewCompaniesPage" time="4.824" classname="edu.itu.bridge.tests.ui.staff.UI_StaffViewPage_OLD"/>
  <testcase name="ui_StaffViewUsersPage" time="3.418" classname="edu.itu.bridge.tests.ui.staff.UI_StaffViewPage_OLD">
    <error type="java.lang.AssertionError" message="expected [JOBS] but found [USERS]">
      <![CDATA[java.lang.AssertionError: expected [JOBS] but found [USERS]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at edu.itu.bridge.tests.base.ActionService.isPresentAndCheckText(ActionService.java:24)
	at edu.itu.bridge.tests.ui.staff.UI_StaffViewPage_OLD.ui_StaffViewUsersPage(UI_StaffViewPage_OLD.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
]]>
    </error>
  </testcase> <!-- ui_StaffViewUsersPage -->
  <testcase name="ui_StaffViewCandidatesPage" time="2.016" classname="edu.itu.bridge.tests.ui.staff.UI_StaffViewPage_OLD">
    <error type="java.lang.AssertionError" message="expected [ITU Bridge] but found [ITU Bridge - Staff UI]">
      <![CDATA[java.lang.AssertionError: expected [ITU Bridge] but found [ITU Bridge - Staff UI]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at edu.itu.bridge.tests.base.BaseTest.checkTitleAndUrl(BaseTest.java:164)
	at edu.itu.bridge.tests.ui.staff.UI_StaffViewPage_OLD.ui_StaffViewCandidatesPage(UI_StaffViewPage_OLD.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
]]>
    </error>
  </testcase> <!-- ui_StaffViewCandidatesPage -->
</testsuite> <!-- edu.itu.bridge.tests.ui.staff.UI_StaffViewPage_OLD -->
